# Generated by Django 5.1.4 on 2025-01-28 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_address',
            field=models.JSONField(default=dict),
        ),
    ]
