# Generated by Django 5.1.4 on 2025-01-11 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermatchingpreferences',
            name='fields_of_interest',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.AlterField(
            model_name='volunteermatchingpreferences',
            name='skills',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
