# Generated by Django 5.1.4 on 2025-02-25 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0002_endorsement_statuspost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='organization_profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/'),
        ),
    ]
