# Generated by Django 5.1.4 on 2025-02-26 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0003_alter_organization_organization_profile_img_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermatchingpreferences',
            name='languages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='volunteermatchingpreferences',
            name='smart_matching_enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.CreateModel(
            name='OrganizationPreferences',
            fields=[
                ('organization_preference_id', models.AutoField(primary_key=True, serialize=False)),
                ('enable_volontera_point_opportunities', models.BooleanField(blank=True, null=True)),
                ('volontera_points_rate', models.FloatField(blank=True, default=1.0, null=True)),
                ('organization', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='volunteers_organizations.organization')),
            ],
        ),
    ]
