# Generated by Django 5.1.4 on 2025-01-11 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0003_alter_volunteermatchingpreferences_fields_of_interest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteermatchingpreferences',
            name='availability',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='volunteermatchingpreferences',
            name='fields_of_interest',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='volunteermatchingpreferences',
            name='preferred_duration',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='volunteermatchingpreferences',
            name='skills',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
