# Generated by Django 5.1.4 on 2025-02-27 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0004_volunteermatchingpreferences_languages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteermatchingpreferences',
            name='location',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
