# Generated by Django 5.1.4 on 2025-01-11 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0004_alter_volunteermatchingpreferences_availability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='organization',
            name='organization_country',
            field=models.TextField(default='United States', max_length=100),
        ),
        migrations.AlterField(
            model_name='organization',
            name='organization_address',
            field=models.TextField(max_length=100),
        ),
    ]
