# Generated by Django 5.1.4 on 2025-02-28 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0005_volunteermatchingpreferences_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationpreferences',
            name='location',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
