# Generated by Django 5.1.4 on 2025-03-06 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0006_organizationpreferences_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteermatchingpreferences',
            name='smart_matching_enabled',
        ),
    ]
