# Generated by Django 5.1.4 on 2025-03-18 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0007_remove_volunteermatchingpreferences_smart_matching_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organizationpreferences',
            name='enable_volontera_point_opportunities',
        ),
        migrations.RemoveField(
            model_name='organizationpreferences',
            name='volontera_points_rate',
        ),
        migrations.AddField(
            model_name='organization',
            name='volontera_points',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='volontera_points',
            field=models.FloatField(default=0),
        ),
        migrations.DeleteModel(
            name='Membership',
        ),
    ]
