# Generated by Django 5.1.4 on 2025-01-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers_organizations', '0008_alter_following_followed_organization_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='membership',
            constraint=models.CheckConstraint(condition=models.Q(('role__in', ['admin', 'opportunity leader', 'member'])), name='valid_role_check'),
        ),
    ]
