# Generated by Django 5.1.4 on 2025-01-09 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_notifs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='user_type',
            field=models.CharField(choices=[('admin', 'Admin'), ('volunteer', 'Volunteer'), ('organization', 'Organization')], max_length=20),
        ),
    ]
