# Generated by Django 5.1.4 on 2025-01-09 09:10

import accounts_notifs.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_notifs', '0002_alter_account_user_type'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('objects', accounts_notifs.models.AccountManager()),
            ],
        ),
    ]
