# Generated by Django 5.1.4 on 2025-01-10 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_notifs', '0004_alter_account_contact_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='username',
        ),
    ]
