# Generated by Django 5.1.4 on 2025-01-10 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_notifs', '0005_remove_account_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountpreferences',
            name='smart_matching_enabled',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
