# Generated by Django 5.1.4 on 2025-01-24 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_notifs', '0006_alter_accountpreferences_smart_matching_enabled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_number',
            field=models.CharField(default=12345678, max_length=15, unique=True),
            preserve_default=False,
        ),
    ]
