# Generated by Django 5.1.4 on 2025-01-24 23:47

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_notifs', '0007_alter_account_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='MT', unique=True),
        ),
    ]
