# Generated by Django 5.1.4 on 2025-01-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_notifs', '0008_alter_account_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='contact_number',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
