# Generated by Django 5.1.4 on 2025-02-26 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_notifs', '0009_alter_account_contact_number'),
    ]

    operations = []
