# Generated by Django 5.1.4 on 2025-03-17 10:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_notifs', '0013_notification_notification_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification_id',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
