# Generated by Django 5.1.4 on 2025-02-01 20:03

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers_organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerEngagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_basis', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person'), ('both', 'Both')], max_length=10)),
                ('duration', models.CharField(choices=[('short-term', 'Short-Term'), ('medium-term', 'Medium-Term'), ('long-term', 'Long-Term')], max_length=20)),
                ('days_of_week', models.JSONField(default=list)),
                ('as_group', models.BooleanField(default=False)),
                ('no_of_additional_volunteers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('engagement_status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='ongoing', max_length=20)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers_organizations.organization')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers_organizations.volunteer')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerEngagementLog',
            fields=[
                ('volunteer_engagement_log_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('no_of_hours', models.FloatField(default=0.5)),
                ('log_notes', models.TextField(default='', max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('volunteer_engagement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities_engagements.volunteerengagement')),
            ],
        ),
        migrations.CreateModel(
            name='VolunteerOpportunity',
            fields=[
                ('volunteer_opportunity_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=500)),
                ('work_basis', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person'), ('both', 'Both')], max_length=10)),
                ('duration', models.CharField(choices=[('short-term', 'Short-Term'), ('medium-term', 'Medium-Term'), ('long-term', 'Long-Term')], max_length=20)),
                ('opportunity_date', models.DateField(blank=True, null=True)),
                ('days_of_week', models.JSONField(blank=True, default=list, null=True)),
                ('area_of_work', models.CharField(max_length=100)),
                ('requirements', models.JSONField(default=list)),
                ('ongoing', models.BooleanField(default=False)),
                ('application_deadline', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('can_apply_as_group', models.BooleanField(default=False)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers_organizations.organization')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerOpportunityApplication',
            fields=[
                ('volunteer_opportunity_application_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_work_basis', models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person'), ('both', 'Both')], max_length=10)),
                ('selected_duration', models.CharField(choices=[('short-term', 'Short-Term'), ('medium-term', 'Medium-Term'), ('long-term', 'Long-Term')], max_length=20)),
                ('selected_days_of_week', models.JSONField(blank=True, default=list, null=True)),
                ('application_status', models.CharField(default='pending', max_length=20)),
                ('as_group', models.BooleanField(default=False)),
                ('no_of_additional_volunteers', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers_organizations.organization')),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='volunteers_organizations.volunteer')),
                ('volunteer_opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities_engagements.volunteeropportunity')),
            ],
        ),
        migrations.AddField(
            model_name='volunteerengagement',
            name='volunteer_opportunity_application',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='opportunities_engagements.volunteeropportunityapplication'),
        ),
        migrations.AddConstraint(
            model_name='volunteeropportunity',
            constraint=models.CheckConstraint(condition=models.Q(('ongoing', False), ('application_deadline__isnull', True), _connector='OR'), name='check_application_deadline_null_if_ongoing'),
        ),
        migrations.AddConstraint(
            model_name='volunteeropportunityapplication',
            constraint=models.UniqueConstraint(fields=('volunteer_opportunity', 'volunteer'), name='unique_volunteer_opportunity_application'),
        ),
    ]
