# Generated by Django 5.1.4 on 2025-03-03 01:07

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0001_initial'),
        ('volunteers_organizations', '0006_organizationpreferences_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='VolunteerOpportunitySession',
            fields=[
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('session_date', models.DateField()),
                ('session_start_time', models.TimeField()),
                ('session_end_time', models.TimeField()),
                ('slots', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ['session_date', 'session_start_time'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerSessionEngagement',
            fields=[
                ('session_engagement_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('cant_go', "Can't Go"), ('can_go', 'Can Go')], default='cant_go', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='volunteerengagement',
            name='as_group',
        ),
        migrations.RemoveField(
            model_name='volunteerengagement',
            name='days_of_week',
        ),
        migrations.RemoveField(
            model_name='volunteerengagement',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='volunteerengagement',
            name='no_of_additional_volunteers',
        ),
        migrations.RemoveField(
            model_name='volunteerengagement',
            name='work_basis',
        ),
        migrations.RemoveField(
            model_name='volunteeropportunityapplication',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='volunteeropportunityapplication',
            name='selected_days_of_week',
        ),
        migrations.RemoveField(
            model_name='volunteeropportunityapplication',
            name='selected_duration',
        ),
        migrations.RemoveField(
            model_name='volunteeropportunityapplication',
            name='selected_work_basis',
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='opportunity_time_from',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='opportunity_time_to',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='required_location',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='slots',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='volunteeropportunity',
            name='status',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteeropportunityapplication',
            name='rationale',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='area_of_work',
            field=models.CharField(choices=[('education', 'Education'), ('health', 'Health'), ('environment', 'Environment'), ('animals', 'Animals'), ('arts', 'Arts'), ('community', 'Community'), ('sports', 'Sports'), ('technology', 'Technology'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='duration',
            field=models.CharField(choices=[('short-term', 'Short-Term'), ('medium-term', 'Medium-Term'), ('long-term', 'Long-Term')], default='short-term', max_length=20),
        ),
        migrations.AlterField(
            model_name='volunteeropportunityapplication',
            name='application_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='volunteerengagement',
            constraint=models.UniqueConstraint(fields=('volunteer_opportunity_application',), name='unique_engagement_per_application'),
        ),
        migrations.AddField(
            model_name='volunteeropportunitysession',
            name='opportunity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities_engagements.volunteeropportunity'),
        ),
        migrations.AddField(
            model_name='volunteerengagementlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities_engagements.volunteeropportunitysession'),
        ),
        migrations.AddConstraint(
            model_name='volunteerengagementlog',
            constraint=models.UniqueConstraint(fields=('volunteer_engagement', 'session', 'created_at'), name='unique_volunteer_log_per_day'),
        ),
        migrations.AddField(
            model_name='volunteersessionengagement',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities_engagements.volunteeropportunitysession'),
        ),
        migrations.AddField(
            model_name='volunteersessionengagement',
            name='volunteer_engagement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='opportunities_engagements.volunteerengagement'),
        ),
        migrations.AddConstraint(
            model_name='volunteersessionengagement',
            constraint=models.UniqueConstraint(fields=('volunteer_engagement', 'session'), name='unique_volunteer_session_engagement'),
        ),
    ]
