# Generated by Django 5.1.4 on 2025-01-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='ongoing',
            field=models.BooleanField(default=False),
        ),
    ]
