# Generated by Django 5.1.4 on 2025-01-13 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0002_volunteeropportunity_ongoing'),
        ('volunteers_organizations', '0009_membership_valid_role_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='opportunity_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='volunteeropportunity',
            constraint=models.CheckConstraint(condition=models.Q(('ongoing', False), ('application_deadline__isnull', True), _connector='OR'), name='check_application_deadline_null_if_ongoing'),
        ),
        migrations.AddConstraint(
            model_name='volunteeropportunity',
            constraint=models.CheckConstraint(condition=models.Q(('ongoing', False), models.Q(('days_of_week__len__gt', 0), ('opportunity_date__isnull', True)), _connector='OR'), name='check_opportunity_date_null_if_ongoing'),
        ),
        migrations.AddConstraint(
            model_name='volunteeropportunity',
            constraint=models.CheckConstraint(condition=models.Q(('ongoing', True), models.Q(('days_of_week__len', 0), ('opportunity_date__isnull', False)), _connector='OR'), name='check_opportunity_date_not_null_if_not_ongoing'),
        ),
    ]
