# Generated by Django 5.1.4 on 2025-03-03 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0002_volunteeropportunitysession_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='volunteerengagementlog',
            name='unique_volunteer_log_per_day',
        ),
        migrations.AddConstraint(
            model_name='volunteerengagementlog',
            constraint=models.UniqueConstraint(fields=('volunteer_engagement', 'session'), name='unique_volunteer_log_per_session'),
        ),
    ]
