# Generated by Django 5.1.4 on 2025-03-03 03:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0003_remove_volunteerengagementlog_unique_volunteer_log_per_day_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerengagementlog',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='opportunities_engagements.volunteersessionengagement'),
        ),
    ]
