# Generated by Django 5.1.4 on 2025-03-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0003_remove_volunteerengagementlog_unique_volunteer_log_per_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteerengagementlog',
            name='is_volunteer_request',
            field=models.BooleanField(default=False),
        ),
    ]
