# Generated by Django 5.1.4 on 2025-01-14 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0004_remove_volunteeropportunity_check_opportunity_date_null_if_ongoing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerengagement',
            name='work_basis',
            field=models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person'), ('both', 'Both')], max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='work_basis',
            field=models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person'), ('both', 'Both')], max_length=10),
        ),
        migrations.AlterField(
            model_name='volunteeropportunityapplication',
            name='selected_work_basis',
            field=models.CharField(choices=[('online', 'Online'), ('in-person', 'In-Person'), ('both', 'Both')], max_length=10),
        ),
    ]
