# Generated by Django 5.1.4 on 2025-03-03 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0004_alter_volunteerengagementlog_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunitysession',
            name='tatus',
            field=models.CharField(choices=[('upcoming', 'Upcoming'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='upcoming', max_length=20),
        ),
    ]
