# Generated by Django 5.1.4 on 2025-03-03 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0005_volunteeropportunitysession_tatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='volunteeropportunitysession',
            old_name='tatus',
            new_name='status',
        ),
    ]
