# Generated by Django 5.1.4 on 2025-01-14 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0005_alter_volunteerengagement_work_basis_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteeropportunity',
            name='days_of_week',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
