# Generated by Django 5.1.4 on 2025-03-04 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opportunities_engagements', '0006_rename_tatus_volunteeropportunitysession_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteeropportunity',
            name='languages',
            field=models.JSONField(default=list),
        ),
    ]
